# Generated by Django 3.2 on 2021-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0004_auto_20210422_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=198, null=True),
        ),
    ]
