# Generated by Django 3.2 on 2021-04-22 05:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=198, null=True)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.product')),
            ],
        ),
    ]
