# Generated by Django 3.2 on 2021-04-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0006_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
