# Generated by Django 3.2 on 2021-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0007_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
