# Generated by Django 3.2 on 2021-04-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0011_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
