# Generated by Django 3.2 on 2021-04-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0016_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
